# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "dYZKJI9ZX3++MtAugewyMXTf76zUwQodDajTzd+vvT+a4fRf0U/8AN2YEztzruDJuwhrxMNH7x2LQ7Fw9FyQs018keyx9nMK8/HdcHHWrBz6/NNxKwzYxyS2q3UnvRto6aecTk0cGAMebqdMW/XQG5bvp2QhjGeC3cqWRH6rTl3iNjhlMCXeVEnVoW44evIxLMKyXP6w0nbnEhr+JVEywncKTGIUJc/WfH4flA83csK6IutvkFjPkrLYuTy2wq59cKS0fMiW6J75PBucWj4HLCpnnu7sn8/ESD/xsuMpd/t2A5cNBFum+iP6Yn1Ieu4lfAgaFP+QVBY8wKoQJb1ON28IaZC1z32m8KCyQ0A43BYMEcBKpeOkPeM1hHm/Dqc+rUzocj2sEWO+2z4jYegbZhQcvLPYZFO114mtHq2ih1/7aJ8lT4UxZHN7Wu6w6Tz5xFVINXLuRGFEpBWbB146htDMgPQi8tNKdIF02FGcuFJlcm2i+wrMghktuVju/CzA2Jd0+bYQ7hp6wu03a1YSvGMgsqJppQA9SEu7Jb5Tq+fSo2LOfaJ6RARyL2OWICtzrxK5JAKSwKJ25R5UwWgtn9nY1lj9qanFn7Muv3lMjmzFil1yq2xkpj/w1Rs/EkLxKx9yn3qRE6S7ciPmPYKpytQFNVYzOfX6tQNn/o4O7Gw="


before_install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
