travis:
  secure:
    BINSTAR_TOKEN: dYZKJI9ZX3++MtAugewyMXTf76zUwQodDajTzd+vvT+a4fRf0U/8AN2YEztzruDJuwhrxMNH7x2LQ7Fw9FyQs018keyx9nMK8/HdcHHWrBz6/NNxKwzYxyS2q3UnvRto6aecTk0cGAMebqdMW/XQG5bvp2QhjGeC3cqWRH6rTl3iNjhlMCXeVEnVoW44evIxLMKyXP6w0nbnEhr+JVEywncKTGIUJc/WfH4flA83csK6IutvkFjPkrLYuTy2wq59cKS0fMiW6J75PBucWj4HLCpnnu7sn8/ESD/xsuMpd/t2A5cNBFum+iP6Yn1Ieu4lfAgaFP+QVBY8wKoQJb1ON28IaZC1z32m8KCyQ0A43BYMEcBKpeOkPeM1hHm/Dqc+rUzocj2sEWO+2z4jYegbZhQcvLPYZFO114mtHq2ih1/7aJ8lT4UxZHN7Wu6w6Tz5xFVINXLuRGFEpBWbB146htDMgPQi8tNKdIF02FGcuFJlcm2i+wrMghktuVju/CzA2Jd0+bYQ7hp6wu03a1YSvGMgsqJppQA9SEu7Jb5Tq+fSo2LOfaJ6RARyL2OWICtzrxK5JAKSwKJ25R5UwWgtn9nY1lj9qanFn7Muv3lMjmzFil1yq2xkpj/w1Rs/EkLxKx9yn3qRE6S7ciPmPYKpytQFNVYzOfX6tQNn/o4O7Gw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
